version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 sync --acl public-read ./dist s3://${DeployBucket}/ --delete
      - >
        aws s3 cp s3://${DeployBucket}/index.html s3://${DeployBucket}/index.html --metadata-directive REPLACE --cache-control max-age=0
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: dist
